### ISSUE TITLE
Option for using the Probe K8s resource

### ISSUE THREAD

**Issue by dabo-ZON** [anas-aso/ssllabs_exporter#29]
Is there an option for using the Kubernetes _probe_ api resource for static prometheus scrape configuration?
This can be useful and would be equal to blackbox_exporter.

`kubectl explain probe.spec`
```
KIND:     Probe
VERSION:  monitoring.coreos.com/v1

RESOURCE: spec <Object>

DESCRIPTION:
     Specification of desired Ingress selection for target discovery by
     Prometheus.

FIELDS:
   basicAuth    <Object>
      password  <Object>
         key    <string>
         name   <string>
         optional       <boolean>
      username  <Object>
         key    <string>
         name   <string>
         optional       <boolean>
   bearerTokenSecret    <Object>
      key       <string>
      name      <string>
      optional  <boolean>
   interval     <string>
   jobName      <string>
   module       <string>
   prober       <Object>
      path      <string>
      scheme    <string>
      url       <string>
   scrapeTimeout        <string>
   targets      <Object>
      ingress   <Object>
         namespaceSelector      <Object>
            any <boolean>
            matchNames  <[]string>
         relabelingConfigs      <[]Object>
            action      <string>
            modulus     <integer>
            regex       <string>
            replacement <string>
            separator   <string>
            sourceLabels        <[]string>
            targetLabel <string>
         selector       <Object>
            matchExpressions    <[]Object>
               key      <string>
               operator <string>
               values   <[]string>
            matchLabels <map[string]string>
      staticConfig      <Object>
         labels <map[string]string>
         relabelingConfigs      <[]Object>
            action      <string>
            modulus     <integer>
            regex       <string>
            replacement <string>
            separator   <string>
            sourceLabels        <[]string>
            targetLabel <string>
         static <[]string>
   tlsConfig    <Object>
      ca        <Object>
         configMap      <Object>
            key <string>
            name        <string>
            optional    <boolean>
         secret <Object>
            key <string>
            name        <string>
            optional    <boolean>
      cert      <Object>
         configMap      <Object>
            key <string>
            name        <string>
            optional    <boolean>
         secret <Object>
            key <string>
            name        <string>
            optional    <boolean>
      insecureSkipVerify        <boolean>
      keySecret <Object>
         key    <string>
         name   <string>
         optional       <boolean>
      serverName        <string>
```

**Comment by dabo-ZON** [comment]
OK yes it's already possible. One example for static targets.

```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ssllabs-exporter
  labels:
    app: ssllabs-exporter
spec:
  interval: 10m
  scrapeTimeout: 10m
  jobName: ssllabs-exporter
  prober:
    url: ssllabs-exporter.monitoring-namespace.svc.cluster.local
  targets:
    staticConfig:
      relabelingConfigs:
        - sourceLabels: [__param_target]
          targetLabel: instance
      static:
        - mygoodratingdomain.com
        - badrates.com
```
