### ISSUE TITLE
use different port

### ISSUE THREAD

**Issue by stefangweichinger** [anas-aso/ssllabs_exporter#41]
Could you provide an example how to run the container within docker-compose and a different port?

I try:

```
##  docker-compose.yml
  ssllabs-exporter:
    image: anasaso/ssllabs_exporter:latest
    ports:
      - 9193:19115
    restart: always
    networks:
      - back-tier
      - front-tier 
```

and I get metrics on http://localhost:9193/metrics

Im prometheus.yml:

```
  - job_name: 'ssllabs-exporter'
    scrape_interval: 10m
    scrape_timeout: 10m
    metrics_path: /probe
    static_configs:
      - targets:
        - github.com
        - ssllabs.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 'ssllabs-exporter:9193'  # change this to the FQDN of ssllabs-exporter
      - source_labels: [__param_target]
        target_label: instance
```

I wonder if the tabs are correct in the example ... and if my quoting of the `FQDN:PORT` should work.
